{{- if .Values.webUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gridwatch.fullname" . }}-web-ui
  labels:
    {{- include "gridwatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  replicas: {{ .Values.webUI.replicaCount }}
  selector:
    matchLabels:
      {{- include "gridwatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-ui
  template:
    metadata:
      labels:
        {{- include "gridwatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web-ui
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gridwatch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: web-ui
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.webUI.image.repository }}:{{ .Values.webUI.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webUI.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webUI.resources | nindent 12 }}
      {{- with .Values.webUI.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webUI.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webUI.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gridwatch.fullname" . }}-web-ui
  labels:
    {{- include "gridwatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
spec:
  type: {{ .Values.webUI.service.type }}
  ports:
    - port: {{ .Values.webUI.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gridwatch.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-ui
{{- end }}
